#!/bin/bash

###
# Automated Network Module Synchronizer (ANMS)
#

export ANMS_HOME
export ANMS_META
export ANMS_LIB_FILE="/tmp/anms.lib.sh"

declare self="$(readlink -f "$0")"
declare address="$1"
declare domain="`sed 's/^[^:]\+:\/\///' <<< $address`"
declare manifest="$address/manifest.yml"
declare yml_prefix="yml_"
declare home="/etc/anms"
declare webdl webchk

declare -A webkit_dl=( [wget]="wget -qO- " [curl]="curl -sS " )
declare -A webkit_chk=( [wget]="wget -S --spider " [curl]="curl --silent -I " )

###
# Checking environment
#
for n in tac sed awk grep tar md5sum; do
    if ! which $n >/dev/null 2>&1; then
        echo "Missing command '$n'" >&2; exit 1
    fi
done

###
# Userly a distro comes with at least one of these. 
# However they do not always pack both.
#
for n in ${!webkit_dl[*]}; do
    if which $n >/dev/null 2>&1; then
        webdl="${webkit_dl[$n]}"
        webchk="${webkit_chk[$n]}"
        
        break
    fi
done

if [ -z "$webdl" ]; then
    echo "Missing wget or curl" >&2; exit 1
    
elif [ -z "$address" ]; then
    echo "Missing server address" >&2; exit 1
    
elif [ ! -d "$home" ]; then
    mkdir "$home"
fi

###
# This function will Parse a simple YAML file
# and will output bash variables
#
# Typical Usage:
# eval $(yml_parse sample.yml)
#
# @author Stefan Farestam
#
yml_parse() {
   local s='[[:space:]]*' w='[a-zA-Z0-9_-]*' fs=$'\034'
   local input="$1"

   sed -ne "s|^\($s\):|\1|" \
        -e 's|`||g;s|\$||g;' \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" $input |
   awk -F$fs '{
      gsub(/^[ \t]+/, "", $3); 
      gsub(/[ \t]+$/, "", $3);
      gsub("-", "_", $2);
         
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {
        if (i > indent) {
            delete vname[i]
        }
      }
      
      vn=""; 
      for (i=0; i<indent; i++) {
        vn=(vn)(vname[i])("_")
      }
      
      printf("declare %s%s%s=\"%s\"\n", "'$yml_prefix'",vn, $2, $3);
   }'
}

###
#
#
yml_defined() {
    local varstr="${yml_prefix}${1}"
    shift
    
    varstr="`printf $varstr $(sed 's/-/_/g' <<<"$@")`"
    
    if [ -n "${!varstr}" ]; then
        return 0
    fi
    
    return 1
}

###
#
#
yml_get() {
    local varstr="${yml_prefix}${1}"
    shift
    
    varstr="`printf $varstr $(sed 's/-/_/g' <<<"$@")`"
    
    echo ${!varstr}
}

###
#
#
yml_cmp() {
    local varstr="${yml_prefix}${1}"
    local cmpstr="$2"
    shift 2
    
    varstr="`printf $varstr $(sed 's/-/_/g' <<<"$@")`"
    
    if [[ "${!varstr}" == "$cmpstr" ]]; then
        return 0
    fi
    
    return 1
}

###
#
#
pkg_install() {
    local mod="$1"
    local file="$2"
    local archive="/tmp/$(basename "$file")"
    local mperm muid mgid mpath scr
    local arg=install
    local hash
    
    echo "Installing module '$mod'"
    $webdl $file > $archive
    hash=`md5sum $archive 2>/dev/null | awk '{print $1}'`
    
    ANMS_HOME="$home/$mod"
    ANMS_META="$ANMS_HOME/META"
    
    if yml_cmp %s_file_md5 "$hash" "$mod"; then    
        if [ ! -d "$ANMS_HOME" ]; then
            mkdir "$ANMS_HOME"
        
        elif [ -f "$ANMS_HOME/files.lst" ]; then
            if [ -f "$ANMS_HOME/meta-files.lst" ]; then
                cp "$ANMS_HOME/meta-files.lst" "$ANMS_HOME/meta-files.old.lst"
            fi
            
            cp "$ANMS_HOME/files.lst" "$ANMS_HOME/files.old.lst"
            echo "" > "$ANMS_HOME/files.lst"
            arg=update
        fi
        
        if [ ! -d "$ANMS_META" ]; then
            mkdir "$ANMS_META"
        fi
        
        echo -e "\tExtracting meta files"
        while read file; do
            if grep -qe '/$' <<< "$file"; then
                if [ ! -d "/$file" ]; then
                    mkdir "/$file"
                fi
            
            else
                tar -xf $archive "$(sed "s|^${ANMS_META:1}/|meta/|" <<< "$file")" -O > "/$file" 2> >(grep -v 'Removing lead' >&2)
            fi
            
        done < <(tar -tf $archive 2>/dev/null | grep -ve '^meta/$' | grep -e '^meta/' | sed "s|^meta/|${ANMS_META:1}/|" | tee "$ANMS_HOME/meta-files.lst")
        
        echo -e "\tRunning pre-install script"
        if tar -tf $archive 2>/dev/null | grep -q '^pre-install\b'; then
            if ! tar -xf $archive 'pre-install' -O 2> >(grep -v 'Removing lead' >&2) | bash -s -- $arg > >(sed 's/\(.*\)/\t\1/') 2> >(sed 's/\(.*\)/\t\1/' >&2); then
                echo -e "\tThe pre-install script failed to run properly" >&2
            fi
        fi
        
        echo -e "\tExtracting source files"
        while read file; do
            if grep -qe '/$' <<< "$file"; then
                if [ ! -d "/$file" ]; then
                    mkdir "/$file"
                fi
            
            else
                tar -xf $archive "src/$file" -O > "/$file" 2> >(grep -v 'Removing lead' >&2)
            fi
            
        done < <(tar -tf $archive 2>/dev/null | grep -ve '^src/$' | grep -e '^src/' | sed 's/^src\///' | tee "$ANMS_HOME/files.lst")
        
        echo -e "\tSetting file permissions"
        if tar -tf $archive 2>/dev/null | grep -qe '^permissions\b'; then
            for perm in `tar -xf $archive 'permissions' -O 2> >(grep -v 'Removing lead' >&2)`; do
                mpath="$(awk -F: '{print $1}' <<< $perm)"
                
                if [ -e "$mpath" ]; then
                    mperm=$(awk -F: '{print $2}' <<< $perm)
                    muid=$(awk -F: '{print $3}' <<< $perm)
                    mgid=$(awk -F: '{print $4}' <<< $perm)
                    
                    if [ -n "$mperm" ]; then
                        chmod $mperm "$mpath" 2>/dev/null
                    fi
                    
                    if [ -n "$muid" ]; then
                        chown $muid "$mpath" 2>/dev/null
                    fi
                    
                    if [ -n "$mgid" ]; then
                        chgrp $mgid "$mpath" 2>/dev/null
                    fi
                    
                else
                    echo -e "\tCould not set permissions on '$mpath'. No such path" >&2
                fi
            done
        fi
        
        echo -e "\tRemoving old files"
        for prefix in meta-files files; do
            if [ -f "$ANMS_HOME/$prefix.old.lst" ]; then
                while read file; do
                    if ! grep -qe "^${file}$" "$ANMS_HOME/$prefix.lst"; then
                        if grep -qe '/$' <<< "$file"; then
                            if [ -d "/$file" ] && [ -z "$(ls -A "/$file")" ]; then
                                rmdir "/$file" 2>/dev/null
                                
                            else
                                echo -e "\tNot removing '/$file'. Directory is not empty" >&2
                            fi
                        
                        else
                            rm "/$file" 2>/dev/null
                        fi
                    fi
                
                done < <(tac "$ANMS_HOME/$prefix.old.lst")
            fi
        done
        
        echo -e "\tRunning install script"
        cat << EOF | tee $ANMS_LIB_FILE >/dev/null
            anms_install() {
                local arg i x
            
                case "\$1" in
                    "src")
                        echo -e "\tExtracting source files from src-\$2"
                        while read file; do
                            if grep -qe '/$' <<< "\$file"; then
                                if [ ! -d "/\$file" ]; then
                                    mkdir "/\$file"
                                fi
                            
                            else
                                tar -xf $archive "src-\$2/\$file" -O > "/\$file" 2> >(grep -v 'Removing lead' >&2)
                            fi
                            
                        done < <(tar -tf $archive 2>/dev/null | grep -ve "^src-\$2/$" | grep -e "^src-\$2/" | sed "s/^src-\$2\///" | tee -a "$ANMS_HOME/files.lst")
                    ;;
                    
                    "ref")
                        echo -e "\tAdding a file reference for '\$2'"
                    
                        if [ -e "\$2" ]; then 
                            arg="\$(realpath --no-symlinks "\$2")"
                            arg="\${arg:1}"
                            i=\$(awk -F/ '{print NF-1}' <<< "\$arg")
                            
                            for ((x=1; x <= i; x++)); do
                                echo "\$(cut -d '/' -f "-\$x" <<< "\$arg")/" >> "$ANMS_HOME/files.lst"
                            done
                            
                            if [[ -d "\$2" && ! -L "\$2" ]]; then
                                echo "\$arg/" >> "$ANMS_HOME/files.lst"
                                
                            else
                                echo "\$arg" >> "$ANMS_HOME/files.lst"
                            fi
                        else
                            echo "Failed to add reference. The path '\$2' does not exist."
                        fi
                    ;;
                esac
            }
EOF
        if tar -tf $archive 2>/dev/null | grep -qe '^install\b'; then
            if ! tar -xf $archive 'install' -O 2> >(grep -v 'Removing lead' >&2) | bash -s -- $arg > >(sed 's/\(.*\)/\t\1/') 2> >(sed 's/\(.*\)/\t\1/' >&2); then
                echo -e "\tThe install script failed to run properly" >&2
            fi
        fi
        
        echo -e "\tFinalizing installation"
        echo $hash > "$ANMS_HOME/hash.md5"
        
        for scr in uninstall post-uninstall; do
		    if tar -tf $archive 2>/dev/null | grep -qe "^$scr\b"; then
		        tar -xf $archive "$scr" -O > "$ANMS_HOME/$scr" 2> >(grep -v 'Removing lead' >&2)
		    fi
		done
		
		awk '!seen[$0]++' $ANMS_HOME/files.lst > $ANMS_HOME/files.lst.tmp
		mv $ANMS_HOME/files.lst.tmp $ANMS_HOME/files.lst

        rm $ANMS_LIB_FILE 2>/dev/null
        rm "$ANMS_HOME/files.old.lst" 2>/dev/null
        rm "$ANMS_HOME/meta-files.old.lst" 2>/dev/null
        rm $archive 2>/dev/null
    
    else
        echo "Mismatch in package checksum for module $mod" >&2; return 1
    fi
}

###
#
#
pkg_uninstall() {
    local mod="$1"
    local file
    
    echo "Uninstalling module '$mod'"
    
    ANMS_HOME="$home/$mod"
    ANMS_META="$ANMS_HOME/META"
    
    echo -e "\tRunning uninstall"
    if [ -f "$ANMS_HOME/uninstall" ]; then
        if ! bash "$ANMS_HOME/uninstall" > >(sed 's/\(.*\)/\t\1/') 2> >(sed 's/\(.*\)/\t\1/' >&2); then
            echo -e "\tThe uninstall failed to run properly" >&2
        fi
    fi
    
    echo -e "\tRemoving source files"
    while read file; do
        if grep -qe '/$' <<< "$file"; then
            if [ -d "/$file" ] && [ -z "$(ls -A "/$file")" ]; then
                rmdir "/$file" 2>/dev/null
                
            else
                echo -e "\tNot removing '/$file'. Directory is not empty" >&2
            fi
        
        else
            rm "/$file" 2>/dev/null
        fi
        
    done < <(tac "$ANMS_HOME/files.lst")
    
    echo -e "\tRunning post-uninstall"
    if [ -f "$ANMS_HOME/post-uninstall" ]; then
        if ! bash "$ANMS_HOME/post-uninstall" > >(sed 's/\(.*\)/\t\1/') 2> >(sed 's/\(.*\)/\t\1/' >&2); then
            echo -e "\tThe post uninstall failed to run properly" >&2
        fi
    fi
    
    echo -e "\tRemoving meta files"
    while read file; do
        if grep -qe '/$' <<< "$file"; then
            if [ -d "/$file" ] && [ -z "$(ls -A "/$file")" ]; then
                rmdir "/$file" 2>/dev/null
                
            else
                echo -e "\tNot removing '/$file'. Directory is not empty" >&2
            fi
        
        else
            rm "/$file" 2>/dev/null
        fi
        
    done < <(tac "$ANMS_HOME/meta-files.lst")
    
    echo -e "\tFinalizing module removal"
    rmdir "$ANMS_META" 2>/dev/null
    rm "$ANMS_HOME"/* 2>/dev/null
    rmdir "$ANMS_HOME" 2>/dev/null
}

###
#
#
{
    echo "Started at `date '+%Y-%m-%d %H:%M'`"
    echo "Contacting the server $domain"

    if ping -q -c 1 -W 1 $domain >/dev/null 2>&1; then
        if $webchk $manifest >/dev/null 2>&1 && $webdl $manifest | tee /tmp/manifest.yml | grep -qe '^[\s ]*modules:'; then
            nhash=`md5sum /tmp/manifest.yml 2>/dev/null | awk '{print $1}'`
            ohash=`cat "$home/manifest.md5" 2>/dev/null`
            
            if [[ "$nhash" != "$ohash" ]]; then
                eval $(yml_parse /tmp/manifest.yml)
                
                echo "Checking for old modules"
                for dir in "$home"/*; do
                    if [ -d "$dir" ]; then
                        mod="`basename "$dir"`"
                        hash=`cat "$home/$mod/hash.md5" 2>/dev/null`

                        if ! [[ " `yml_get modules` " =~ " $mod " ]]; then
                            for defmod in `yml_get modules`; do
                                if yml_cmp %s_file_md5 "$hash" "$defmod"; then
                                    echo "Renaming module `basename "$mod"` -> $defmod"
                                    mv "$home/$mod" "$home/$defmod"
                                    
                                    continue 2
                                fi
                            done
                        
                            pkg_uninstall $mod
                        fi
                    fi
                done
                
                echo "Checking for new/updated modules"
                for mod in `yml_get modules`; do
                    if ! yml_defined %s_condition $mod || eval $(yml_get %s_condition $mod) >/dev/null 2>&1; then
                        hash=`cat "$home/$mod/hash.md5" 2>/dev/null`
                        
                        if yml_defined %s_file_path $mod && ! yml_cmp %s_file_md5 "$hash" "$mod"; then
                            pkgfile="$address/$(yml_get %s_file_path $mod)"
                            
                            if $webchk $pkgfile >/dev/null 2>&1; then
                                pkg_install $mod $pkgfile
                                
                                if yml_defined %s_respawn $mod && yml_cmp %s_respawn "true" "$mod"; then
                                    echo "Respawning the process"
                                    exec bash "$self" "$address"
                                fi
                            
                            else
                                echo "No package is defined for the module $mod" >&2
                            fi
                        
                        elif ! yml_defined %s_file_path $mod; then
                            echo "No package is available for the module $mod" >&2
                        fi
                    
                    elif yml_defined %s_condition $mod && [ -d "$home/$mod" ]; then
                        pkg_uninstall $mod
                    fi
                done
                
                echo $nhash > "$home/manifest.md5"
            
            else
                echo "No changes was detected"
            fi
            
            rm /tmp/manifest.yml 2>/dev/null
        
        else
            echo "Manifest resource is unavailable" >&2; exit 1
        fi
        
    else
        echo "Connection timed out" >&2; exit 1
    fi

    echo "Sync complete"
    
    exit
}
